apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-proj
  labels:
     app: httpd-proj

spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-proj

  template:
    metadata:
      labels:
        app: httpd-proj
    spec:
      containers:
      - name: httpd-proj
        image: divakar2201/httpd-proj:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
