
---
- name: create new container and tag and push to repo
  hosts: ansible


  tasks:
  - name: Create docker image
    command: docker build -t git-proj:latest .
    args:
     chdir: /opt/docker/httpd-proj

  - name: Create tag and push to docker hub
    command: docker tag git-proj:latest divakar2201/git-proj:latest
    ignore_errors: yes

  - name: push image to docker
    command: docker push divakar2201/git-proj:latest
    ignore_errors: yes
